[2022-05-31 01:19:31,130] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: lesson1.exercise6.create_table manual__2022-05-31T01:19:30.338662+00:00 [queued]>
[2022-05-31 01:19:31,146] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: lesson1.exercise6.create_table manual__2022-05-31T01:19:30.338662+00:00 [queued]>
[2022-05-31 01:19:31,147] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-05-31 01:19:31,147] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-05-31 01:19:31,147] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-05-31 01:19:31,157] {taskinstance.py:1262} INFO - Executing <Task(PostgresOperator): create_table> on 2022-05-31 01:19:30.338662+00:00
[2022-05-31 01:19:31,164] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'lesson1.exercise6', 'create_table', 'manual__2022-05-31T01:19:30.338662+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launches.py', '--cfg-path', '/tmp/tmpbkdm5yse', '--error-file', '/tmp/tmp_ft2_339']
[2022-05-31 01:19:31,165] {standard_task_runner.py:77} INFO - Job 12: Subtask create_table
[2022-05-31 01:19:31,161] {standard_task_runner.py:52} INFO - Started process 29220 to run task
[2022-05-31 01:19:31,207] {logging_mixin.py:109} INFO - Running <TaskInstance: lesson1.exercise6.create_table manual__2022-05-31T01:19:30.338662+00:00 [running]> on host b6b47ea722e0
[2022-05-31 01:19:31,251] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=lesson1.exercise6
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-05-31T01:19:30.338662+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-31T01:19:30.338662+00:00
[2022-05-31 01:19:31,261] {base.py:79} INFO - Using connection to: id: redshift. Host: redshift-cluster-1.ctwsihrera0y.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: ***, extra: {}
[2022-05-31 01:19:32,745] {dbapi.py:225} INFO - Running statement: 
CREATE TABLE IF NOT EXISTS trips (
trip_id INTEGER NOT NULL,
start_time TIMESTAMP NOT NULL,
end_time TIMESTAMP NOT NULL,
bikeid INTEGER NOT NULL,
tripduration DECIMAL(16,2) NOT NULL,
from_station_id INTEGER NOT NULL,
from_station_name VARCHAR(100) NOT NULL,
to_station_id INTEGER NOT NULL,
to_station_name VARCHAR(100) NOT NULL,
usertype VARCHAR(20),
gender VARCHAR(6),
birthyear INTEGER,
PRIMARY KEY(trip_id))
DISTSTYLE ALL;, parameters: None
[2022-05-31 01:19:33,359] {postgres.py:71} INFO - INFO:  Relation "trips" already exists and will be skipped

[2022-05-31 01:19:33,369] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=lesson1.exercise6, task_id=create_table, execution_date=20220531T011930, start_date=20220531T011931, end_date=20220531T011933
[2022-05-31 01:19:33,400] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-31 01:19:33,436] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
